MovieDatabaseSDA/MovieDatabaseSDA/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import hello
from core.views import welcome
from core.views import MovieCreateView, MovieUpdateView, MovieDeleteView
# from core.views import MovieView
from .views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello),
    path('welcome/', welcome),
    path('', IndexView.as_view(), name='index'),
    path("core/", include("core.urls", namespace="core")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
]

# path('', MovieView.as_view(), name='index'),
# path('', movies, name='index'),

MovieDatabaseSDA/core/urls.py
from django.contrib import admin
from django.urls import path
from core.views import hello
from core.views import welcome
from core.views import MovieCreateView, MovieUpdateView, MovieDeleteView, MovieListView, MovieDetailView
# from core.views import MovieView

app_name = 'core'

urlpatterns = [
    path("movie/list", MovieListView.as_view(), name='movie_list'),
    path("movie/detail/<pk>", MovieDetailView.as_view(), name='movie_detail'),
    path("movie/create", MovieCreateView.as_view(), name='movie_create'),
    path("movie/update/<pk>", MovieUpdateView.as_view(), name='movie_update'),
    path("movie/delete/<pk>", MovieDeleteView.as_view(), name='movie_delete'),
]

MovieDatabaseSDA/core/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from model_utils import Choices

AGE_LIMITS = Choices(
    (0, 'kids', 'children'),
    (1, 'teens', 'teenagers'),
    (2, 'adults', 'adult people'),
)


class Country(models.Model):
    name = models.TextField(max_length=30, default='USA', unique=True)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name


class BoxOffice(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE, default=Country)
    amount = models.DecimalField(max_digits=20, decimal_places=2)

    def __str__(self):
        return f"{self.country} - {self.amount} of money"


class Director(models.Model):
    name = models.CharField(max_length=20)
    surname = models.CharField(max_length=30)
    birth_date = models.DateField(null=True, blank=True)
    rating = models.IntegerField(
        null=True, validators=[MaxValueValidator(10), MinValueValidator(1)]
    )

    class Meta:
        unique_together = ('name', 'surname')

    def __str__(self):
        return self.name + " " + self.surname


class Genre(models.Model):
    name = models.CharField(max_length=20, unique=True)
    age_limit = models.IntegerField(
        choices=AGE_LIMITS,
        blank=True,
        null=True)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=70)
    rating = models.IntegerField(
        null=True, blank=True, validators=[MaxValueValidator(10), MinValueValidator(1)]
    )
    released = models.DateField()
    description = models.TextField(null=True, blank=True)
    # null do baz danych a blank do formularzy
    created = models.DateTimeField(auto_now_add=True)
    genre = models.ForeignKey(Genre, null=True, on_delete=models.SET_NULL, blank=True)
    director = models.ForeignKey(Director, null=True, on_delete=models.SET_NULL, blank=True)
    countries = models.ManyToManyField(Country, 'movies')
    boxoffices = models.ManyToManyField(BoxOffice, 'movies', blank=True)

    class Meta:
        unique_together = ('title', 'released', 'director')
        ordering = ('title',)

    def __str__(self):
        return f"{self.title} from {self.released}"

MovieDatabaseSDA/core/forms.py
import re
from datetime import date

from crispy_forms.bootstrap import FormActions, InlineCheckboxes
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, Div, MultiField, Button
from django import forms

from core.models import Genre, Movie
from django.core.exceptions import ValidationError


def capitalized_validator(value: str):
    if value[0].islower():
        raise ValidationError("Value must be capitalized.")


class PastMonthField(forms.DateField):
    def validate(self, value):
        super().validate(value)
        if value >= date.today():
            raise ValidationError('Only past dates allowed here.')

    def clean(self, value):
        result = super().clean(value)
        return date(year=result.year, month=result.month, day=1)


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = "__all__"
        # fields = ("title", "rating", "released")

    title = forms.CharField(max_length=100, validators=[capitalized_validator])
    genre = forms.ModelChoiceField(queryset=Genre.objects.all())
    rating = forms.IntegerField(min_value=1, max_value=10)
    released = PastMonthField()
    description = forms.CharField(widget=forms.Textarea, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'title',
            Row(Column('genre'), Column('rating'), Column('released')),
            'director',
            'description',
            Div('countries', css_id = 'black-fields'),
            FormActions(
                Submit('submit', 'Submit'),
                Button('cancel', 'Cancel')
            ),
            InlineCheckboxes('boxoffices')
        )

    def clean_description(self):  # clean_<fieldname>
        initial = self.cleaned_data['description']
        sentences = re.sub(r'\s*\.\s*', '.', initial).split('.')
        cleaned = '.'.join(sentence.capitalize() for sentence in sentences)
        return cleaned

    def clean(self):
        result = super().clean()
        if result['genre'].name == 'comedy' and result['rating'] >= 5:
            raise ValidationError("The best comedy is worth a 4")
        return result

MovieDatabaseSDA/core/views.py
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.http import HttpResponse
from django.shortcuts import render
from django import views
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, FormView, CreateView, UpdateView, DeleteView, DetailView

from core.models import Movie, AGE_LIMITS
from core.forms import MovieForm
import logging


logging.basicConfig(filename='log.txt',
                    filemode='w',
                    level=logging.INFO,
                    )
LOGGER = logging.getLogger(__name__)


class StaffRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff


# class MovieCreateView(FormView):
#     template_name = 'form.html'
#     form_class = MovieForm
#     success_url = reverse_lazy('movie_create')  # from django.urls
#
#     def form_valid(self, form):
#         result = super().form_valid(form)
#         cleaned_data = form.cleaned_data
#         Movie.objects.create(
#             title=cleaned_data['title'],
#             genre=cleaned_data['genre'],
#             rating=cleaned_data['rating'],
#             released=cleaned_data['released'],
#             description=cleaned_data['description'],
#         )
#         return result

class MovieCreateView(LoginRequiredMixin, CreateView):
    title = 'Add movie'
    template_name = 'form.html'
    form_class = MovieForm
    success_url = reverse_lazy('core:movie_list')

    def form_invalid(self, form):
        LOGGER.warning("Invalid data provided")
        return super().form_invalid(form)

    def post(self, request, *args, **kwargs):
        result = super().post(request, *args, **kwargs)
        LOGGER.info(f"Movie titled {request.__dict__['_post']['title']} was added")
        return result


class MovieUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'form.html'
    model = Movie
    form_class = MovieForm
    success_url = reverse_lazy('core:movie_list')

    def form_invalid(self, form):
        LOGGER.warning("Invalid data provided")
        return super().form_invalid(form)


class MovieDeleteView(LoginRequiredMixin, StaffRequiredMixin, DeleteView):
    template_name = 'movie_confirm_delete.html'
    model = Movie
    success_url = reverse_lazy('core:movie_list')

    def test_func(self):
        return super().test_func() and self.request.user.is_superuser


def welcome(request):
    return HttpResponse(f"Welcome Paulina 2 and 2 is {2 * 2}")


#
# def hello(request):
#     return HttpResponse("Hello world you maniac")

def hello(request):
    LOGGER.warning("\n\nCos smiesznego. Wrreszczie dzialalalalal sasasasa")
    return render(request,
                  template_name='hello.html',
                  context={'adjectives': ['beautiful', 'wonderful', 'maniac', 'cruel', 'nice']},
                  )


# def movies(request):
#     return render(request,
#                   template_name='movies.html',
#                   context={'movies': Movie.objects.all(), 'age_limits': AGE_LIMITS})


# class MovieView(views.View):
#     def get(self, request):
#         return render(request,
#                       template_name='movies.html',
#                       context={'movies': Movie.objects.all()})

# class MovieView(TemplateView):
#     template_name = 'movies.html'
#     extra_context = {'movies': Movie.objects.all(), 'age_limits': AGE_LIMITS}


# class MovieView(ListView):
#     template_name = 'movies.html'
#     model = Movie
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['age_limits'] = AGE_LIMITS
#         return context

class MovieListView(ListView):
    template_name = 'movie_list.html'
    model = Movie


class MovieDetailView(DetailView):
    template_name = 'movie_detail.html'
    model = Movie

MovieDatabaseSDA/core/templates/base.html
{% load bootstrap4 %}
{% load static %}
​
<html {% if LANGUAGE_CODE %}lang="{{ LANGUAGE_CODE }}"{% endif %}>
​
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Django Movies</title>
      {% block styles %}{% bootstrap_css %}{% endblock %}
      {% block scripts %}{% bootstrap_javascript jquery='full' %}{% endblock %}
  </head>
​
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container fixed">
<!--        <a class="navbar-brand" href="/">Django Movies</a> bezposredni link!!!-->
        <a class="navbar-brand" href="{% url 'index' %}">Django Training Movie Database</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="/">
              Home
            </a>
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="jumbotron">
        {% block content %}{% endblock %}
      </div>
    </div>
  </body>
​
</html>

MovieDatabaseSDA/core/templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello, world</title>
</head>
<body>

<h1>Hello, my friend...</h1>
    {% for adjective in adjectives %}
        {% if adjective != 'cruel' %}
            <p>This is a {{ adjective }} world...</p>
        {% endif %}
    {% endfor %}

</body>
</html>

</body>
</html>

MovieDatabaseSDA/core/templates/movie_confirm_delete.html
{% extends "base.html" %}
​
{% load bootstrap4 %}
​
{% block content %}
  <form method="post">
      {% csrf_token %}
      <p>
          Are you sure you want to delete movie "{{ object.title }}" from the database?
      </p>
      <input type="submit" value="Yes" class="btn btn-danger">
      </form>
      <form method="get" action="/core/movie/list">
    <button type="submit" class="btn btn-success">No</button>
    </form>


{% endblock %}

MovieDatabaseSDA/core/templates/movie_detail.html
{% extends "base.html" %}

{% load movie_extras %}

{% block content %}
  {{ movie|attr_as_p:'title' }}
  {{ movie|attr_as_p:'released' }}
  {{ movie|attr_as_p:'genre' }}
  {{ movie|attr_as_p:'rating' }}
  {{ movie|attr_as_p:'description' }}
<!--  <p><strong>Title:</strong> {{ object.title }}</p>-->
<!--  <p><strong>Released:</strong> {{ object.released }}</p>-->
<!--  <p><strong>Genre:</strong> {{ object.genre }}</p>-->
<!--  <p><strong>Rating:</strong> {{ object.rating }}</p>-->
<!--  <p><strong>Description:</strong> {{ object.description }}</p>-->
{% endblock %}

MovieDatabaseSDA/core/templates/movie_list.html
{% extends "base.html" %}

{% load movie_extras %}

{% block content %}
  <ul>
    {% for movie in object_list %}
      <li>
        {% movie_format movie short=False %}
        <a href="{% url 'core:movie_detail' movie.pk %}">detail</a> /
        <a href="{% url 'core:movie_update' movie.pk %}">update</a> /
        <a href="{% url 'core:movie_delete' movie.pk %}">delete</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

<!--        {{ movie.title }} ({{ movie.released.year }})-->

MovieDatabaseSDA/core/templates/movies.html
{% extends 'base.html' %}

{% block content %}
<h1>Welcome to Django training movies</h1>
<ul>
    {% for movie in object_list %}
    <li>
        {{ movie.title }} from {{ movie.released.year }} directed by {{ movie.director }}<br><br>
        {% if movie.genre.age_limit != age_limits.kids or movie.genre.age_limit == age_limits.kids %}
        Genre: {{ movie.genre }}<br>
        Description: {{ movie.description }}<br>
        Rating by best viewers: {{ movie.rating }}<br>
        <br>

        {% else %}
        Not for kids!<br><br><br>
        {% endif %}
    </li>

    {% endfor %}

</ul>
{% endblock %}